version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'monthly'
      target-branch: 'main'
      labels:
          - 'npm dependencies'
      commit-message:
          prefix: 'chore'
          include: 'scope'