name: Website Deployment

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: mittelbots

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run build

